# Generated by Django 5.1.1 on 2025-11-04 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = []
