# Generated by Django 5.1.1 on 2025-11-05 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_productcategory_and_update_product"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="pointbalance",
            name="unique_user_local_points",
        ),
        migrations.AlterUniqueTogether(
            name="pointbalance",
            unique_together={("user", "local")},
        ),
    ]
