# Generated by Django 5.1.1 on 2025-11-05 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_product_inventory_notifications"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["category", "display_order", "name"]},
        ),
        migrations.RenameIndex(
            model_name="product",
            new_name="api_product_categor_6f4b32_idx",
            old_name="api_prod_cat_display_idx",
        ),
        migrations.RenameIndex(
            model_name="product",
            new_name="api_product_local_i_d5a733_idx",
            old_name="api_prod_loc_display_idx",
        ),
    ]
