# Generated by Django 5.1.1 on 2025-11-05 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_single_local_scope'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('icon', models.CharField(blank=True, max_length=40)),
                ('scope', models.CharField(choices=[('general', 'General'), ('product', 'Producto'), ('local', 'Local')], default='general', max_length=20)),
                ('accent_color', models.CharField(blank=True, max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='local',
            name='amenities_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='local',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='local',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='local',
            name='cover_image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='local',
            name='facebook_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='local',
            name='gallery_urls',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='local',
            name='headline',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='local',
            name='highlights',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='local',
            name='instagram_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='local',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='local',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='local',
            name='map_embed_code',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='local',
            name='map_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='local',
            name='opening_hours',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='local',
            name='reservation_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='local',
            name='special_hours',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='local',
            name='tiktok_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='local',
            name='timezone',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='local',
            name='website_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='local',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='local',
            name='wifi_network',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='local',
            name='wifi_password',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='local',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='locals', to='api.tag'),
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='products', to='api.tag'),
        ),
    ]
